Talend/puppet-tic

- Gemfile.lock
- examples/frontend.pp
- manifests/frontend20.pp
- manifests/frontend20/config.pp
- manifests/frontend20/params.pp
- spec/acceptance/frontend_spec.rb
- templates/srv/tomcat/ipaas-srv/webapps/ipaas/config/config.js.erb
set variables set variables MIXPANEL_ENABLED: true and PENDO_ENABLED: true
https://jira.talendforge.org/browse/DEVOPS-2902
https://jira.talendforge.org/browse/DEVOPS-2899
> Add variables to config.js

- manifests/frontend/install.pp
- spec/acceptance/frontend_spec.rb
> DEVOPS-3228 update tomcat version for frontend

- Gemfile.lock
- manifests/frontend/install.pp
- manifests/services/service.pp
- spec/acceptance/frontend_spec.rb
- spec/acceptance/services_spec.rb
Small configuration change + fix for failed tests
> DEVOPS-3525: Replace -XX:MaxPermSize => -XX:MaxMetaspaceSize; fix tests

- examples/frontend.pp
- manifests/frontend.pp
- manifests/frontend/config.pp
- manifests/frontend/params.pp
- spec/acceptance/frontend_spec.rb
> DEVOPS-3602: Add frontend zipkin properties

- examples/services.pp
- manifests/services.pp
- manifests/services/config.pp
- manifests/services/params.pp
- spec/acceptance/services_spec.rb
> DEVOPS-3703: Add iPaaS runtime zipkin properties

- examples/services.pp
- manifests/services/features/webhooks_client.pp
- spec/acceptance/services_spec.rb
> DEVOPS-3766: Add webhook client config

- README.md
- manifests/frontend/config.pp
- spec/acceptance/frontend_spec.rb
> DEVOPS-3926: Remove ROOT webapp in frontend tomcat config

- manifests/frontend/config.pp
- spec/acceptance/frontend_spec.rb
> DEVOPS-3953: Frontend properties changes

- .kitchen.yml
- examples/frontend.pp
- manifests/frontend.pp
- manifests/frontend/config.pp
- manifests/frontend/params.pp
- spec/acceptance/frontend_spec.rb
- templates/srv/tomcat/ipaas-srv/webapps/ipaas/config/config.js.erb
> DEVOPS-4677: Add Data Streams URL for Frontend

- .kitchen.yml
- manifests/frontend/config.pp
- manifests/frontend/install.pp
- spec/acceptance/frontend_spec.rb
> DEVOPS-4670: Add config for ipaas-user.war and ipaas-workspaces.war

- .kitchen.yml
- manifests/frontend/config.pp
- manifests/frontend/install.pp
- spec/acceptance/frontend_spec.rb
> Revert "DEVOPS-4670: Add config for ipaas-user.war and ipaas-workspaces.war"

- .kitchen.yml
- manifests/services.pp
- manifests/services/features/data_transfer_service_core.pp
- manifests/services/params.pp
> DEVOPS-5034: Remove test data bucket

- examples/services.pp
- manifests/services.pp
- manifests/services/features/dispatcher_core.pp
- manifests/services/params.pp
- spec/acceptance/services_spec.rb
> DEVOPS-5487: Add dispatcher redis config

- manifests/frontend/install.pp
- spec/acceptance/frontend_spec.rb
Add talend-ipaas-web-tasks-and-plans-administration installation
> DEVOPS-5537 : Add talend-ipaas-web-tasks-and-plans-administration installation

- manifests/frontend/config.pp
Add Tmc url parameters in new app
> DEVOPS-5537 : Add Tmc url parameters in new app

- manifests/frontend/config.pp
> DEVOPS-5537: Add talend-ipaas-web-tasks-and-plans-administration installation

- manifests/frontend/config.pp
> DEVOPS-5537: Fix fo double apply

- examples/services.pp
- manifests/services.pp
- manifests/services/features/dispatcher_core.pp
- manifests/services/params.pp
- spec/acceptance/services_spec.rb
Add kafka Apps Support and Topics and Fix
> Add kafka Apps Support and Topics

- manifests/frontend/config.pp
- spec/acceptance/frontend_spec.rb
Copying logic of s3 template to ipaas-server
> TMC-16463: Add tic s3 template to ipaas-server

- .kitchen.yml
- manifests/services/init_configuration_service.pp
- templates/var/tmp/init_configuration_service.json.erb
Tested on INT by manually changed files applied puppet
> DEVOPS-6049: migrate to TPSVC Configuration Service

- manifests/services/features/notification_subscription_service.pp
- spec/acceptance/services_spec.rb
This revert of code will allow both usage of memcached and redis
> TMC-16522: Revert change to allow both memcached and redis

- examples/frontend.pp
- manifests/frontend.pp
- manifests/frontend/config.pp
- manifests/frontend/params.pp
- spec/acceptance/frontend_spec.rb
Frontend integration with Hashicorp vault
https://jira.talendforge.org/browse/DEVOPS-7139
> frontend to vault

- manifests/services/config.pp
The kafka reference was not the good one KAfka App needed
> DEVOPS-7554: Fix Kafka server

- templates/srv/tomcat/ipaas-srv/webapps/ipaas/resources/tic_s3_access.template.erb
https://jira.talendforge.org/browse/TMC-16612 - MANAGEMENT CONSOLE EXPORT LOGS : Test fails with "Error: Test upload into the external S3 bucket failed."
> TMC-16612 + policy to get customer's bucket region

- manifests/engine.pp
- manifests/engine/config.pp
- manifests/engine/params.pp
- templates/opt/talend/ipaas/rt-infra/etc/org.talend.ipaas.rt.dispatcher.nodemanager.aws.cfg.erb
> Revert "Add Amq Log DNS"

- manifests/services/features/plan_executor_service.pp
https://jira.talendforge.org/browse/DEVOPS-10131
> DEVOPS-10131 add redis connection to plan executor service
